### ISSUE TITLE
[Linux] 执行 npm run compile 报错

### ISSUE THREAD

**Issue by keleyundou** [FlowCI/docs#29]
``` node
> node build/scripts/compile

module.js:545
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/colabean/Desktop/workspace/flow-web/build/scripts/compile.js:1:74)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flow-web@0.0.1 compile: `node build/scripts/compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flow-web@0.0.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

手动执行 `npm install fs-extra` 还是不行

**Comment by xueerfei** [comment]
我也遇到同样的问题，
1. rm -rf /node_modules
2. npm install fs-extra -S   //不要全局安装
